# Generated by Django 6.0.3 on 2026-04-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_capacity_alter_course_code_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
